name: manage-azure-policy-e2be9e85
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/_CD_Cognitive_Services_accounts_should_disable_public_network_access_a1ef77ce-ba42-4ffd-9aff-1b8efb66d449/**'
#      - .github/workflows/manage-azure-policy-e2be9e85.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_e2be9e85}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/_CD_Cognitive_Services_accounts_should_disable_public_network_access_a1ef77ce-ba42-4ffd-9aff-1b8efb66d449/**
