name: manage-azure-policy-39f77bd3
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/_CD_API_App_should_only_be_accessible_over_HTTPS_8e6d44c8-68e7-4d81-ab42-fed6036ca3a5/**'
#      - .github/workflows/manage-azure-policy-39f77bd3.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_39f77bd3}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/_CD_API_App_should_only_be_accessible_over_HTTPS_8e6d44c8-68e7-4d81-ab42-fed6036ca3a5/**
